project:
  type: website
  output-dir: docs
  render:
    - wettkaempfe.qmd
    - bike.qmd
    - run.qmd
    - hike.qmd
    - bikerun.qmd
    - skitouren.qmd
    - kieser.qmd
    - langlauf.qmd
    - zusammenfassungen.qmd
    - saisonstart.qmd
    - travel.qmd
    - summary_winter.qmd
    
website:
  title: "Sport Kaspar"
  navbar:
    left:
    - text: "Wettkaempfe"
      href: wettkaempfe.html
    - text: "Ausdauer"
      menu:
        - text: "Bike"
          href: bike.html
        - text: "Run"
          href: run.html
        - text: "Wandern"
          href: hike.html
        - text: "Bike & Run"
          href: bikerun.html
        - text: "Skitouren"
          href: skitouren.html
        - text: "Langlauf"
          href: langlauf.html
    - text: "Kieser"
      href: kieser.html
    - text: "Zusammenfassungen"
      href: zusammenfassungen.html
    - text: "Saisonl√§nge"
      href: saisonstart.html
    - text: "Zusammenfassung Winter"
      href: summary_winter.html
    right:
      - icon: github
        href: https://github.com/numbersman77/litreview

format:
  html:
    theme:
    - cosmo
    - custom.scss
    css: styles.css
    toc: true
    mainfont: Verdana
    fontsize: 0.9em
    toc-location: "left"
    number-sections: true
    highlight-style: pygments
    tbl-cap-location: bottom
    grid:
      sidebar-width: 400px
      body-width: 1000px
      margin-width: 100px

editor: source

